# Generated by Django 2.1 on 2018-09-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Olymp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('level', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Univer_plus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('f_title', models.CharField(max_length=200)),
                ('s_title', models.CharField(max_length=200, null=True)),
                ('passing_score', models.PositiveSmallIntegerField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('privilege', models.CharField(max_length=200, null=True)),
                ('army_cafedra', models.BooleanField()),
                ('exams', models.ManyToManyField(to='olcalc.Subject')),
                ('olymps', models.ManyToManyField(blank=True, to='olcalc.Olymp')),
            ],
        ),
    ]
