# Generated by Django 2.0.7 on 2018-07-20 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='univer_plus',
            name='exams',
            field=models.ManyToManyField(to='olcalc.Subject'),
        ),
    ]
