# Generated by Django 2.1 on 2018-08-03 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testolymp',
            name='subject',
        ),
        migrations.DeleteModel(
            name='TestSubject',
        ),
    ]
