# Generated by Django 2.1 on 2018-09-21 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univer_plus',
            name='privilege',
            field=models.CharField(default='Нет', max_length=200),
        ),
    ]
