# Generated by Django 2.1 on 2018-09-21 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univer_plus',
            name='exams',
            field=models.ManyToManyField(blank=True, to='olcalc.Subject'),
        ),
        migrations.AlterField(
            model_name='univer_plus',
            name='f_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='univer_plus',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True),
        ),
    ]
