# Generated by Django 2.1 on 2018-09-01 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='univer_plus',
            name='army_cafedra',
        ),
        migrations.RemoveField(
            model_name='univer_plus',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='univer_plus',
            name='f_title',
        ),
    ]
