# Generated by Django 2.0.7 on 2018-07-23 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univer_plus',
            name='olymps',
            field=models.ManyToManyField(null=True, to='olcalc.Olymp'),
        ),
        migrations.AlterField(
            model_name='univer_plus',
            name='s_title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
