# Generated by Django 2.0.7 on 2018-07-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='olymps',
        ),
        migrations.AddField(
            model_name='faculty',
            name='olymps',
            field=models.ManyToManyField(to='olcalc.Olymp'),
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='specialities',
        ),
        migrations.AddField(
            model_name='faculty',
            name='specialities',
            field=models.ManyToManyField(to='olcalc.Speciality'),
        ),
        migrations.RemoveField(
            model_name='olymp',
            name='subject',
        ),
        migrations.AddField(
            model_name='olymp',
            name='subject',
            field=models.ManyToManyField(to='olcalc.Subject'),
        ),
    ]
