# Generated by Django 2.1 on 2018-09-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0002_auto_20180901_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univer_plus',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
