# Generated by Django 2.1 on 2018-09-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0002_auto_20180921_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univer_plus',
            name='army_cafedra',
            field=models.BooleanField(null=True),
        ),
    ]
