# Generated by Django 2.1 on 2018-10-08 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0002_auto_20180921_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFaculty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('olymps', models.ManyToManyField(blank=True, to='olcalc.Olymp')),
            ],
        ),
        migrations.CreateModel(
            name='TestUniver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('f_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olcalc.TestFaculty')),
            ],
        ),
    ]
