# Generated by Django 2.0.7 on 2018-07-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0002_auto_20180723_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='univer_plus',
            name='privilege',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
