# Generated by Django 2.1 on 2018-08-04 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0002_auto_20180803_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='univerplus',
            name='army_cafedra',
        ),
        migrations.RemoveField(
            model_name='univerplus',
            name='exams',
        ),
        migrations.RemoveField(
            model_name='univerplus',
            name='f_title',
        ),
        migrations.RemoveField(
            model_name='univerplus',
            name='privilege',
        ),
        migrations.RemoveField(
            model_name='univerplus',
            name='rating',
        ),
    ]
