# Generated by Django 2.0.7 on 2018-07-20 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0002_univer_plus_exams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='univer_plus',
            old_name='u_title',
            new_name='title',
        ),
    ]
