# Generated by Django 2.1 on 2018-10-08 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0003_testfaculty_testuniver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testuniver',
            name='f_title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='olcalc.TestFaculty'),
        ),
    ]
