# Generated by Django 2.1 on 2018-08-05 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0003_auto_20180804_1608'),
    ]

    operations = [
        migrations.RenameField(
            model_name='univerplus',
            old_name='s_title',
            new_name='speciality',
        ),
    ]
