# Generated by Django 2.1 on 2018-09-21 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0003_auto_20180921_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univer_plus',
            name='f_title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='univer_plus',
            name='rating',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
