# Generated by Django 2.0.7 on 2018-07-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0003_univer_plus_privilege'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univer_plus',
            name='olymps',
            field=models.ManyToManyField(blank=True, to='olcalc.Olymp'),
        ),
    ]
