# Generated by Django 2.0.7 on 2018-07-25 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0004_auto_20180724_1930'),
    ]

    operations = [
        migrations.CreateModel(
            name='testOlymp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('profile', models.CharField(max_length=200)),
                ('level', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='testSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='testolymp',
            name='subject',
            field=models.ManyToManyField(to='olcalc.testSubject'),
        ),
    ]
