# Generated by Django 2.1 on 2018-09-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0004_auto_20180902_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univer_plus',
            name='privilege',
            field=models.CharField(default=0, max_length=200),
        ),
    ]
