# Generated by Django 2.1.4 on 2018-12-29 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0005_auto_20181229_2302'),
    ]

    operations = [
        migrations.CreateModel(
            name='QSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='qolymp',
            name='subject',
        ),
        migrations.AddField(
            model_name='qolymp',
            name='subject',
            field=models.ManyToManyField(to='olcalc.QSubject'),
        ),
    ]
