# Generated by Django 2.1.4 on 2018-12-30 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0006_auto_20181229_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qolymp',
            name='subject',
        ),
        migrations.AddField(
            model_name='qolymp',
            name='subject',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.DeleteModel(
            name='QSubject',
        ),
    ]
