# Generated by Django 2.1.4 on 2018-12-30 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0007_auto_20181230_2042'),
    ]

    operations = [
        migrations.CreateModel(
            name='QSpeciality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olcalc.QFaculty')),
            ],
        ),
    ]
