# Generated by Django 2.1.4 on 2019-01-01 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0010_qplace'),
    ]

    operations = [
        migrations.AddField(
            model_name='qmapping',
            name='place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='olcalc.QPlace'),
        ),
        migrations.AlterField(
            model_name='qplace',
            name='title',
            field=models.PositiveIntegerField(),
        ),
    ]
