# Generated by Django 2.1.4 on 2019-01-01 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olcalc', '0011_auto_20190101_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qmapping',
            name='place',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='olcalc.QPlace'),
        ),
        migrations.AlterField(
            model_name='qplace',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
